# Étape unique pour le dev : on garde Node
FROM node:22.16.0

# Crée un dossier de travail
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .


EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
