services:
  dashboard_api:
    build: ./modules/dashboard_api
    container_name: regis_dashboard_api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  dashboard_front:
    build: ./modules/dashboard_front
    container_name: regis_dashboard_front
    ports:
      - "8080:80"
    depends_on:
      - dashboard_api
    restart: unless-stopped