services:
  dashboard_api:
    volumes:
      - ./modules/dashboard_api/app:/app/app
      - ./config:/app/config
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  dashboard_front:
    build:
      context: ./modules/dashboard_front
      dockerfile: Dockerfile.dev

    ports:
      - "5173:5173"
    volumes:
      - ./modules/dashboard_front:/app
      - /app/node_modules
    command: npm run dev -- --host
